#11


In [ ]:
pip install rarfile


In [ ]:
import rarfile

# Define path to the .rar file and extraction directory
rar_path = '/content/BrainTumor.rar'
extraction_dir = '/content/BrainTumor/'

# Create extraction directory if it doesn't exist
if not os.path.exists(extraction_dir):
    os.makedirs(extraction_dir)

# Extract the .rar file
with rarfile.RarFile(rar_path) as rf:
    rf.extractall(extraction_dir)

print("Extraction complete.")


Extraction complete.


In [ ]:
import numpy as np
import cv2
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Define the paths to the directories containing the images
path_no = '/content/BrainTumor/BrainTumor/brain_tumor_dataset/no'
path_yes = '/content/BrainTumor/BrainTumor/brain_tumor_dataset/yes'

def extract_features_and_labels(path_no, path_yes):
    features = []
    labels = []

    # Process "no" images
    for filename in os.listdir(path_no):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            img = cv2.imread(os.path.join(path_no, filename), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img = cv2.resize(img, (64, 64))  # Resize to a fixed size
                features.append(img.flatten())
                labels.append(0)  # Label for "no" class

    # Process "yes" images
    for filename in os.listdir(path_yes):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            img = cv2.imread(os.path.join(path_yes, filename), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img = cv2.resize(img, (64, 64))  # Resize to a fixed size
                features.append(img.flatten())
                labels.append(1)  # Label for "yes" class

    return np.array(features), np.array(labels)

# Extract features and labels
features, labels = extract_features_and_labels(path_no, path_yes)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)

print("Data extraction and preparation complete.")


Data extraction and preparation complete.


In [ ]:
import numpy as np
import cv2
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Define the paths to the directories containing the images
path_no = '/content/BrainTumor/BrainTumor/brain_tumor_dataset/no'
path_yes = '/content/BrainTumor/BrainTumor/brain_tumor_dataset/yes'

def extract_features_and_labels(path_no, path_yes):
    features = []
    labels = []

    # Process "no" images
    for filename in os.listdir(path_no):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            img = cv2.imread(os.path.join(path_no, filename), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img = cv2.resize(img, (64, 64))  # Resize to a fixed size
                features.append(img.flatten())
                labels.append(0)  # Label for "no" class

    # Process "yes" images
    for filename in os.listdir(path_yes):
        if filename.endswith('.jpg') or filename.endswith('.png'):
            img = cv2.imread(os.path.join(path_yes, filename), cv2.IMREAD_GRAYSCALE)
            if img is not None:
                img = cv2.resize(img, (64, 64))  # Resize to a fixed size
                features.append(img.flatten())
                labels.append(1)  # Label for "yes" class

    return np.array(features), np.array(labels)

# Extract features and labels
features, labels = extract_features_and_labels(path_no, path_yes)

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=42)


In [ ]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, f1_score, precision_score, recall_score
from sklearn.model_selection import cross_val_score, KFold

# Initialize models
knn = KNeighborsClassifier(n_neighbors=5)
decision_tree = DecisionTreeClassifier()
naive_bayes = GaussianNB()

# Define K-Fold Cross-Validation
kf = KFold(n_splits=10, shuffle=True, random_state=42)

# Function to evaluate models
def evaluate_model(model, X_train, y_train, X_test, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)

    print(f"{model.__class__.__name__}:")
    print("Accuracy:", accuracy)
    print("Confusion Matrix:\n", conf_matrix)
    print("F1 Score:", f1)
    print("Precision:", precision)
    print("Recall:", recall)
    print()

    # K-Fold Cross-Validation
    cv_scores = cross_val_score(model, features, labels, cv=kf)
    print(f"Cross-Validation Scores (K-Fold): {cv_scores}")
    print(f"Mean CV Accuracy: {np.mean(cv_scores)}")
    print("==="*10)

    return accuracy, conf_matrix, f1, precision, recall, cv_scores




In [ ]:
# Evaluate each model
evaluate_model(knn, X_train, y_train, X_test, y_test)


KNeighborsClassifier:
Accuracy: 0.7714285714285715
Confusion Matrix:
 [[17  3]
 [ 5 10]]
F1 Score: 0.7142857142857142
Precision: 0.7692307692307693
Recall: 0.6666666666666666

Cross-Validation Scores (K-Fold): [0.88888889 0.77777778 0.55555556 0.70588235 0.76470588 0.58823529
 0.76470588 0.76470588 0.82352941 0.64705882]
Mean CV Accuracy: 0.7281045751633987


(0.7714285714285715,
 array([[17,  3],
        [ 5, 10]]),
 0.7142857142857142,
 0.7692307692307693,
 0.6666666666666666,
 array([0.88888889, 0.77777778, 0.55555556, 0.70588235, 0.76470588,
        0.58823529, 0.76470588, 0.76470588, 0.82352941, 0.64705882]))

In [ ]:
evaluate_model(decision_tree, X_train, y_train, X_test, y_test)


DecisionTreeClassifier:
Accuracy: 0.7714285714285715
Confusion Matrix:
 [[14  6]
 [ 2 13]]
F1 Score: 0.7647058823529413
Precision: 0.6842105263157895
Recall: 0.8666666666666667

Cross-Validation Scores (K-Fold): [0.77777778 0.83333333 0.61111111 0.70588235 0.82352941 0.58823529
 0.52941176 0.70588235 0.88235294 0.76470588]
Mean CV Accuracy: 0.7222222222222222


(0.7714285714285715,
 array([[14,  6],
        [ 2, 13]]),
 0.7647058823529413,
 0.6842105263157895,
 0.8666666666666667,
 array([0.77777778, 0.83333333, 0.61111111, 0.70588235, 0.82352941,
        0.58823529, 0.52941176, 0.70588235, 0.88235294, 0.76470588]))

In [ ]:
evaluate_model(naive_bayes, X_train, y_train, X_test, y_test)

GaussianNB:
Accuracy: 0.6857142857142857
Confusion Matrix:
 [[16  4]
 [ 7  8]]
F1 Score: 0.5925925925925926
Precision: 0.6666666666666666
Recall: 0.5333333333333333

Cross-Validation Scores (K-Fold): [0.83333333 0.66666667 0.61111111 0.70588235 0.58823529 0.58823529
 0.88235294 0.70588235 0.82352941 0.88235294]
Mean CV Accuracy: 0.7287581699346404


(0.6857142857142857,
 array([[16,  4],
        [ 7,  8]]),
 0.5925925925925926,
 0.6666666666666666,
 0.5333333333333333,
 array([0.83333333, 0.66666667, 0.61111111, 0.70588235, 0.58823529,
        0.58823529, 0.88235294, 0.70588235, 0.82352941, 0.88235294]))